### ISSUE TITLE
Future scope & direction of flake8-async

### ISSUE THREAD

**Issue by jakkdl** [cooperlees/flake8-async#8]
Pulling this out of #6 since it's of a larger scope than just that PR @Zac-HD @cooperlees 

> So I'm wondering if we should instead just lean into the tension, merge this as-is and maybe declare that flake8-async is for asyncio, and we can add similar logic with specific suggested alternatives to flake8-trio later.

Reimplementing some funtionality across the libraries isn't too much work, though is a major pain for maintenance and bugs and stuff. So I'd love to have some more clarity on what the relationship between these two plugins should be, esp as it's kinda muddled if they're both just owned by Zac (and mostly coded by me :sweat_smile:)
Should trio users run both plugins?
Should non-trio users use flake8-trio?
Should any functionality in flake8-trio not specifically for trio be re-created over here?
Straight up merge them and take a config parameter to turn on library-specific functionality? (defaulting to off, but giving a message if not explicitly set and a library is detected as imported)
What's the scope and future of this plugin in general anyway, a plugin with only a single check and a couple dozen lines looks a bit silly.

And if this project leans into being for asyncio, should the plugin be renamed flake8-asyncio? In which case what should we recommend users of libs other than trio/asyncio do? Run both? Neither?

Idk how widely used either plugin is either, but presumably users might have opinions too.

**Comment by jakkdl** [comment]
Ah I see now it was briefly discussed in #2

**Comment by Zac-HD** [comment]
Yep, per https://github.com/cooperlees/flake8-async/pull/6#discussion_r1014857707 let's keep `flake8-async` generic / framework-agnostic.

**Comment by jakkdl** [comment]
Okay that answers some, though not all of my questions. Do we want `trio` users to also use flake8-async? If not, should we duplicate logic between the repos or e.g. do submodule stuff.

And how should e.g. #5 be handled since that's `asyncio`-specific, create `flake8-asyncio`, create a parameter? When I wrote 
> Straight up merge them and take a config parameter to turn on library-specific functionality? (defaulting to off, but giving a message if not explicitly set and a library is detected as imported)

I quite liked that idea, and means we can put `trio` stuff in here too (and suggest users install both) without having to duplicate logic for stuff that's common in several async libs. trio107/108 and possible more could be moved here too.

**Comment by Zac-HD** [comment]
Currently as a Trio user I'm running both, but I think that if we add much more here I'd want to duplicate the logic in flake8-trio because that would allow for much more precise suggested alternatives, which is pretty important for new-to-async teammates.

More generally this feels like a case where abstraction or configuration options 'costs more' than just learning from each and copying a bit of bit of code back and forth between separate specialized implementations.

**Comment by jakkdl** [comment]
Oh but doesn't #5 need config or something anyway? Or declare it out of scope for this and create flake8-asyncio?

**Comment by Zac-HD** [comment]
It's about keeping the return value from `asyncio.create_task()` (in a variable or a list or whatever), so I think you can have a precise check for that function without needing any config options.  The trouble is when you want to do something different depending on the framework *and can't tell* which framework you're currently using.
